### ISSUE TITLE
Deploy script is failing 

### ISSUE THREAD

**Issue by tasiameleshko** [matter-labs/l2-intro-pre-ethdenver#6]
Hi!

`yarn hardhat deploy-zksync --script deploy-greeter.ts` 
fails with error
`Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32602,\"message\":\"Invalid params: missing field 'gasPerPubdata'.\"},\"id\":44}\n", error={"code":-32602}...`

I found in [changelog](https://v2-docs.zksync.io/dev/troubleshooting/changelog.html#system-update-v1-3-feb-8th-2023) that **ergsPerPubdata** should be updated to **gasPerPubdata**, but it's not used directly anywhere in this project, so I assume it's a dependancy issue.

**Comment by tasiameleshko** [comment]
Updating `zksync-web3` to version `0.13.0` fixes the issue. It was mentioned in the changelog, but I missed it for some reason.

**Comment by uF4No** [comment]
Hey 👋 Thanks for creating the issue. You're right, the new version of zksync-web3 is required as we've released some updates in the system. I'll update the project 🤙

**Comment by uF4No** [comment]
This should be resolved now
